// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/auth/callback": {
            "get": {
                "description": "接收 Etsy 返回的 code 和 state，换取 Token 并入库",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth (授权模块)"
                ],
                "summary": "Etsy 授权回调",
                "parameters": [
                    {
                        "type": "string",
                        "description": "授权码",
                        "name": "code",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "安全校验码",
                        "name": "state",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "授权成功信息",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "拒绝授权/参数错误",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/products": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Product"
                ],
                "summary": "获取指定店铺的商品列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "店铺 ID",
                        "name": "shop_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "页码 (默认1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "每页数量 (默认20)",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/etsy_dev_v1_202512_core_view.ProductListResp"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "get": {
                "description": "为指定的预置店铺生成授权链接，并生成 OAuth 授权跳转链接",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth (授权模块)"
                ],
                "summary": "获取 Etsy 授权链接",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "预置的店铺 ID (Database Primary Key)",
                        "name": "shop_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "点击按钮手动复制链接 url",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "etsy_dev_v1_202512_core_view.ProductListResp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 0
                },
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/etsy_dev_v1_202512_core_view.ProductResp"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "success"
                },
                "page": {
                    "type": "integer",
                    "example": 1
                },
                "page_size": {
                    "type": "integer",
                    "example": 20
                },
                "total": {
                    "type": "integer",
                    "example": 100
                }
            }
        },
        "etsy_dev_v1_202512_core_view.ProductResp": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "img_url": {
                    "description": "暂时留空，后续可以加",
                    "type": "string"
                },
                "last_updated": {
                    "type": "string"
                },
                "listing_id": {
                    "description": "这里的 ID 转字符串防止前端大数精度丢失",
                    "type": "string"
                },
                "price": {
                    "description": "组合字段：直接给前端一个浮点数价格",
                    "type": "number"
                },
                "quantity": {
                    "type": "integer"
                },
                "state": {
                    "type": "string"
                },
                "tags": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "title": {
                    "type": "string"
                },
                "views": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
